/*
 * timeline.js — claude-quest. The storyboard as data.
 * 1920x1080 (240x135 game px at PX=8), 60 fps (the console's refresh), 120 bpm, 40 s = 20 bars, 17 shots.
 * At 60 fps a beat is 30 frames, an 8th 15 and a 16th 7.5 (every 8th lands on a frame).
 * All shots mode 'none': pixel art takes no grain post.
 */
(function () {
  'use strict';
  const FILM = (window.FILM = window.FILM || {});
  FILM.TIMELINE = {
    title: 'claude-quest',
    bpm: 120,
    duration: 40,
    fps: 60,
    width: 1920,
    height: 1080,
    shots: [
      { id: 'title', file: '01-title.js', start: 0, end: 2.0, mode: 'none', title: 'CLAUDE QUEST title card',
        brief: 'Black card, CLAUDE QUEST types on, PRESS START blinks, Claw’d idle below.' },
      { id: 'start-run', file: '02-start-run.js', start: 2.0, end: 4.5, mode: 'none', title: 'World 1-1',
        brief: 'Overworld, HUD pops on, Claw’d idles then runs right; camera scrolls; a bug enters.' },
      { id: 'stomp', file: '03-stomp.js', start: 4.5, end: 6.5, mode: 'none', title: 'First stomp',
        brief: 'Jump at T 4.75, stomp the bug at T 5.5 (+100), bounce, keep running.' },
      { id: 'qblock', file: '04-qblock.js', start: 6.5, end: 9.0, mode: 'none', title: '? block',
        brief: 'Head-bump the ? block at T 7.5: coin pops, ×01, +200; block becomes used.' },
      { id: 'powerup', file: '05-powerup.js', start: 9.0, end: 11.5, mode: 'none', title: 'Sparkle mushroom',
        brief: 'Bump at T 10.0 releases the mushroom; at T 11.0 Claw’d powers up to Super (scale 2), +1000.' },
      { id: 'pit', file: '06-pit.js', start: 11.5, end: 13.5, mode: 'none', title: 'The pit',
        brief: 'Super Claw’d long-jumps a 2-tile ground gap (T 12.25–13.25).' },
      { id: 'stairs', file: '07-stairs.js', start: 13.5, end: 16.0, mode: 'none', title: 'Staircase',
        brief: 'Four hops up block columns on beats T 14.0–15.5, stands on the plateau.' },
      { id: 'shell', file: '08-shell.js', start: 16.0, end: 18.5, mode: 'none', title: 'Shell combo',
        brief: 'Stomp the shellbug T 17.0, kick the shell T 17.5, it clears two bugs T 18.0/18.5 (+200/+400).' },
      { id: 'pipe-down', file: '09-pipe-down.js', start: 18.5, end: 21.0, mode: 'none', title: 'Down the pipe',
        brief: 'Jump onto the tall pipe T 19.25–20.25, stand, sink in T 20.5–21.0.' },
      { id: 'cave', file: '10-cave.js', start: 21.0, end: 24.0, mode: 'none', title: 'Underground',
        brief: 'Cave room: five coins collected on beats T 21.5–23.5, hop the bug at T 23.5.',
        transitionIn: { kind: 'fade', dur: 0.25 } },
      { id: 'pipe-up', file: '11-pipe-up.js', start: 24.0, end: 26.0, mode: 'none', title: 'Back to daylight',
        brief: 'Rise out of the pipe T 24.0–24.75, hop down, run; castle and flagpole enter frame right.',
        transitionIn: { kind: 'fade', dur: 0.25 } },
      { id: 'flagpole', file: '12-flagpole.js', start: 26.0, end: 28.0, mode: 'none', title: 'The leap',
        brief: 'Sprint, soar at T 27.0, grab the pole top at T 27.75.' },
      { id: 'slide', file: '13-slide.js', start: 28.0, end: 30.0, mode: 'none', title: 'Flag slide',
        brief: 'Slide down the pole, +5000 at T 28.75, fireworks T 29.0/29.5, hop off and run.' },
      { id: 'castle-in', file: '14-castle-in.js', start: 30.0, end: 32.0, mode: 'none', title: 'Into the castle',
        brief: 'Run the last stretch and vanish through the castle door by T 31.75.' },
      { id: 'throne', file: '15-throne.js', start: 32.0, end: 35.0, mode: 'none', title: 'Princess Pearl',
        brief: 'Castle hall: Claw’d finds Pearl on her pedestal, hearts rise, she waves.',
        transitionIn: { kind: 'fade', dur: 0.25 } },
      { id: 'thanks', file: '16-thanks.js', start: 35.0, end: 38.0, mode: 'none', title: 'Thank you',
        brief: 'THANK YOU CLAW’D! types on, +10000 bonus at T 36.0, both heroes bounce.' },
      { id: 'end-card', file: '17-end-card.js', start: 38.0, end: 40.0, mode: 'none', title: 'Game complete',
        brief: 'Title layout revisited with the princess; PRESS START TO PLAY AGAIN blinks.' },
    ],
    cues: [
      { t: 0.5, kind: 'hit', note: 'title jingle: square-wave arpeggio climbing C5 E5 G5 C6 in 16ths' },
      { t: 1.0, kind: 'sfx', note: 'sparkle ping (high sine ~2 kHz, 80 ms)' },
      { t: 1.5, kind: 'sfx', note: 'sparkle ping again' },
      { t: 2.0, kind: 'cut', note: 'run theme starts: bouncy original chiptune, square lead + triangle bass, through shot 09' },
      { t: 3.5, kind: 'sfx', note: 'bug waddle two-note motif' },
      { t: 5.5, kind: 'hit', note: 'stomp: 100 ms noise squish, 300→80 Hz drop, plus +100 blip E6' },
      { t: 7.5, kind: 'hit', note: 'block bump thud 120 Hz + coin pling B5→E6' },
      { t: 9.5, kind: 'sfx', note: 'jump whoosh' },
      { t: 10.0, kind: 'hit', note: 'mushroom emerge: rising slide 200→900 Hz, 300 ms' },
      { t: 11.0, kind: 'hit', note: 'power-up arpeggio C5 E5 G5 C6 E6 in 16ths + shimmer' },
      { t: 12.25, kind: 'sfx', note: 'long jump whoosh' },
      { t: 13.25, kind: 'sfx', note: 'land thud' },
      { t: 14.0, kind: 'sfx', note: 'stair hop boip 300 Hz' },
      { t: 14.5, kind: 'sfx', note: 'stair hop boip 380 Hz' },
      { t: 15.0, kind: 'sfx', note: 'stair hop boip 460 Hz' },
      { t: 15.5, kind: 'sfx', note: 'stair hop boip 540 Hz' },
      { t: 17.0, kind: 'hit', note: 'stomp squish' },
      { t: 17.5, kind: 'sfx', note: 'shell kick tok 800 Hz' },
      { t: 18.0, kind: 'sfx', note: 'combo hit G5' },
      { t: 18.5, kind: 'sfx', note: 'combo hit B5' },
      { t: 19.25, kind: 'sfx', note: 'jump whoosh' },
      { t: 20.5, kind: 'hit', note: 'pipe entry: three descending glugs 400/300/200 Hz; run theme cuts' },
      { t: 21.0, kind: 'cut', note: 'cave theme: sparse minor square-bass groove' },
      { t: 21.5, kind: 'sfx', note: 'coin pling 1 of 5 (ascending)' },
      { t: 22.0, kind: 'sfx', note: 'coin pling 2' },
      { t: 22.5, kind: 'sfx', note: 'coin pling 3' },
      { t: 23.0, kind: 'sfx', note: 'coin pling 4' },
      { t: 23.5, kind: 'sfx', note: 'coin pling 5 + hop' },
      { t: 24.0, kind: 'sfx', note: 'pipe rise glug 200→400 Hz' },
      { t: 25.0, kind: 'cut', note: 'run theme resumes, doubled an octave up' },
      { t: 27.0, kind: 'sfx', note: 'big jump whoosh' },
      { t: 27.75, kind: 'hit', note: 'pole grab zang: square chord stab C5+E5' },
      { t: 28.0, kind: 'sfx', note: 'slide whistle down 900→300 Hz over 0.7 s' },
      { t: 28.75, kind: 'hit', note: '+5000 score tally arpeggio' },
      { t: 29.0, kind: 'sfx', note: 'firework pop 1' },
      { t: 29.5, kind: 'sfx', note: 'firework pop 2' },
      { t: 30.0, kind: 'cut', note: 'castle fanfare: square-brass figure C5 F5 A5 C6' },
      { t: 31.75, kind: 'sfx', note: 'door clunk' },
      { t: 32.0, kind: 'cut', note: 'throne-room waltz: soft triangle lead, 3/4 feel' },
      { t: 33.0, kind: 'sfx', note: '“!” pling' },
      { t: 34.0, kind: 'sfx', note: 'three heart pops, rising pitch' },
      { t: 35.0, kind: 'cut', note: 'victory fanfare: title jingle rhythm up a fourth' },
      { t: 36.0, kind: 'hit', note: '+10000 bonus tally cascade' },
      { t: 37.0, kind: 'sfx', note: 'sparkle burst' },
      { t: 37.5, kind: 'sfx', note: 'sparkle burst' },
      { t: 38.0, kind: 'cut', note: 'title jingle reprise' },
      { t: 39.5, kind: 'sfx', note: 'final coin ping, rings out' },
    ],
  };
})();
