#!/usr/bin/env node
// clips.cjs : embed short video clips as numbered WebP stills into src/clips.js (instrument mode).
//
//   node tools/clips.cjs                  reads assets/clips.json, writes src/clips.js
//   node tools/clips.cjs --fixtures       reads tools/fixtures/clips.json, writes tools/fixtures/clips.js
//
// assets/clips.json : [{ "id": "kelp", "src": "assets/video/kelp.mp4", "from": 0.5, "to": 3.0, "size": 640 }]
//   src   path from the project root (the fixtures resolve from tools/fixtures)
//   from  seconds into the source (default 0); to: end in seconds (default the whole clip)
//   size  longest side in px (default 640); fps is always the film's (FILM.TIMELINE.fps, default 24)
//   q     WebP quality (default 78)
//   speed playback rate (default 1): 2 plays the [from, to) span in half the time, to fit a slot
//
// Each clip becomes FILM.CLIPS[id] = { w, h, fps, frames: [data URI, ...] }. Scenes draw a frame with
// FILM.clipFrame(id, t) and must declare it in def.clips(t, info) so the frame is decoded before the
// draw (see core.js). Frames are WebP: ffmpeg's libwebp when present, otherwise PNG through
// Python/Pillow.
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const C = require('./common.cjs');

const fixtures = process.argv.includes('--fixtures');
const base = fixtures ? path.join(__dirname, 'fixtures') : C.ROOT;
const manifest = fixtures ? path.join(base, 'clips.json') : path.join(C.ROOT, 'assets', 'clips.json');
const OUT = fixtures ? path.join(base, 'clips.js') : path.join(C.SRC, 'clips.js');
const FFMPEG = process.env.FFMPEG || 'ffmpeg';
const tlFile = path.join(fixtures ? base : C.SRC, 'timeline.js');
const FPS = fs.existsSync(tlFile) ? C.loadTimeline(tlFile).fps : C.FPS;

if (!fs.existsSync(manifest)) {
  console.error(`clips: ${path.relative(C.ROOT, manifest)} is missing (a list of { id, src, from, to, size })`);
  process.exit(1);
}
const list = JSON.parse(fs.readFileSync(manifest, 'utf8'));
const hasLibwebp = /libwebp/.test(spawnSync(FFMPEG, ['-hide_banner', '-encoders'], { encoding: 'utf8' }).stdout || '');

function run(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`${cmd} ${args.join(' ')}\n${r.stderr || r.stdout}`);
  return r.stdout;
}

function webpSize(buf) {
  const kind = buf.toString('ascii', 12, 16);
  if (kind === 'VP8X') return { w: 1 + buf.readUIntLE(24, 3), h: 1 + buf.readUIntLE(27, 3) };
  if (kind === 'VP8L') {
    const b = buf.readUInt32LE(21);
    return { w: 1 + (b & 0x3fff), h: 1 + ((b >> 14) & 0x3fff) };
  }
  if (kind === 'VP8 ') return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
  throw new Error(`unknown WebP chunk ${kind}`);
}

const lines = [
  `/* ${path.basename(OUT)} : GENERATED by tools/clips.cjs from ${path.relative(C.ROOT, manifest)}. Do not edit. */`,
  '(function () {',
  "  'use strict';",
  '  const K = window.FILM.CLIPS;',
];
let total = 0;
for (const c of list) {
  const src = path.resolve(base, c.src);
  if (!fs.existsSync(src)) throw new Error(`clip '${c.id}': ${c.src} not found`);
  const size = c.size || 640;
  const q = c.q || 78;
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), `clip-${c.id}-`));
  const args = ['-v', 'error', '-y'];
  if (c.from) args.push('-ss', String(c.from));
  if (c.to != null) args.push('-t', String(c.to - (c.from || 0))); // input side: the span read, before any speed change
  args.push('-i', src);
  const speed = c.speed || 1;
  const vf = `setpts=PTS/${speed},fps=${FPS},scale='if(gt(iw,ih),${size},-2)':'if(gt(iw,ih),-2,${size})':flags=lanczos`;
  if (hasLibwebp) {
    run(FFMPEG, [...args, '-vf', vf, '-c:v', 'libwebp', '-quality', String(q), '-compression_level', '6', path.join(tmp, 'f%04d.webp')]);
  } else {
    run(FFMPEG, [...args, '-vf', vf, path.join(tmp, 'f%04d.png')]);
    run('python3', ['-c', `import glob,os\nfrom PIL import Image\nfor f in sorted(glob.glob(os.path.join(${JSON.stringify(tmp)},'*.png'))):\n  Image.open(f).convert('RGB').save(f[:-4]+'.webp','WEBP',quality=${q},method=6); os.remove(f)`]);
  }
  const frames = fs.readdirSync(tmp).filter((f) => f.endsWith('.webp')).sort();
  if (!frames.length) throw new Error(`clip '${c.id}': no frames extracted`);
  const bufs = frames.map((f) => fs.readFileSync(path.join(tmp, f)));
  const { w, h } = webpSize(bufs[0]);
  const bytes = bufs.reduce((a, b) => a + b.length, 0);
  total += bytes;
  lines.push(`  K[${JSON.stringify(c.id)}] = { w: ${w}, h: ${h}, fps: ${FPS}, frames: [`);
  for (const b of bufs) lines.push(`    'data:image/webp;base64,${b.toString('base64')}',`);
  lines.push('  ] };');
  fs.rmSync(tmp, { recursive: true, force: true });
  console.log(`  ${c.id}  ${w}x${h}  ${bufs.length} frames (${(bufs.length / FPS).toFixed(2)} s${speed !== 1 ? ` at ${speed}x` : ''})  ${(bytes / 1024).toFixed(0)} KB`);
}
lines.push('})();', '');
fs.writeFileSync(OUT, lines.join('\n'));
console.log(`${list.length} clip(s) -> ${path.relative(C.ROOT, OUT)} (${(total / 1024 / 1024).toFixed(2)} MB of frames)`);
